# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='command.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\rcommand.proto\".\n\ncarCommand\x12\x10\n\x08velocity\x18\x01 \x02(\x02\x12\x0e\n\x06\x64\x65gree\x18\x02 \x02(\x02\"*\n\rcameraCommand\x12\n\n\x02up\x18\x01 \x02(\x02\x12\r\n\x05right\x18\x02 \x02(\x02\"\x1a\n\x0clightCommand\x12\n\n\x02on\x18\x01 \x02(\x08\"*\n\narmCommand\x12\x0c\n\x04goUp\x18\x01 \x02(\x08\x12\x0e\n\x06goDown\x18\x02 \x02(\x08\"{\n\x07\x63ommand\x12\x18\n\x03\x63\x61r\x18\x01 \x02(\x0b\x32\x0b.carCommand\x12\x1e\n\x06\x63\x61mera\x18\x02 \x02(\x0b\x32\x0e.cameraCommand\x12\x18\n\x03\x61rm\x18\x03 \x02(\x0b\x32\x0b.armCommand\x12\x1c\n\x05light\x18\x04 \x02(\x0b\x32\r.lightCommand'
)




_CARCOMMAND = _descriptor.Descriptor(
  name='carCommand',
  full_name='carCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='velocity', full_name='carCommand.velocity', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='degree', full_name='carCommand.degree', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=63,
)


_CAMERACOMMAND = _descriptor.Descriptor(
  name='cameraCommand',
  full_name='cameraCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='up', full_name='cameraCommand.up', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='cameraCommand.right', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=107,
)


_LIGHTCOMMAND = _descriptor.Descriptor(
  name='lightCommand',
  full_name='lightCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='on', full_name='lightCommand.on', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=135,
)


_ARMCOMMAND = _descriptor.Descriptor(
  name='armCommand',
  full_name='armCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goUp', full_name='armCommand.goUp', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goDown', full_name='armCommand.goDown', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=179,
)


_COMMAND = _descriptor.Descriptor(
  name='command',
  full_name='command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='car', full_name='command.car', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera', full_name='command.camera', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arm', full_name='command.arm', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='light', full_name='command.light', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=304,
)

_COMMAND.fields_by_name['car'].message_type = _CARCOMMAND
_COMMAND.fields_by_name['camera'].message_type = _CAMERACOMMAND
_COMMAND.fields_by_name['arm'].message_type = _ARMCOMMAND
_COMMAND.fields_by_name['light'].message_type = _LIGHTCOMMAND
DESCRIPTOR.message_types_by_name['carCommand'] = _CARCOMMAND
DESCRIPTOR.message_types_by_name['cameraCommand'] = _CAMERACOMMAND
DESCRIPTOR.message_types_by_name['lightCommand'] = _LIGHTCOMMAND
DESCRIPTOR.message_types_by_name['armCommand'] = _ARMCOMMAND
DESCRIPTOR.message_types_by_name['command'] = _COMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

carCommand = _reflection.GeneratedProtocolMessageType('carCommand', (_message.Message,), {
  'DESCRIPTOR' : _CARCOMMAND,
  '__module__' : 'command_pb2'
  # @@protoc_insertion_point(class_scope:carCommand)
  })
_sym_db.RegisterMessage(carCommand)

cameraCommand = _reflection.GeneratedProtocolMessageType('cameraCommand', (_message.Message,), {
  'DESCRIPTOR' : _CAMERACOMMAND,
  '__module__' : 'command_pb2'
  # @@protoc_insertion_point(class_scope:cameraCommand)
  })
_sym_db.RegisterMessage(cameraCommand)

lightCommand = _reflection.GeneratedProtocolMessageType('lightCommand', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTCOMMAND,
  '__module__' : 'command_pb2'
  # @@protoc_insertion_point(class_scope:lightCommand)
  })
_sym_db.RegisterMessage(lightCommand)

armCommand = _reflection.GeneratedProtocolMessageType('armCommand', (_message.Message,), {
  'DESCRIPTOR' : _ARMCOMMAND,
  '__module__' : 'command_pb2'
  # @@protoc_insertion_point(class_scope:armCommand)
  })
_sym_db.RegisterMessage(armCommand)

command = _reflection.GeneratedProtocolMessageType('command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'command_pb2'
  # @@protoc_insertion_point(class_scope:command)
  })
_sym_db.RegisterMessage(command)


# @@protoc_insertion_point(module_scope)
