# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_detection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_detection.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x17message_detection.proto\"#\n\x11message_detection\x12\x0e\n\x06result\x18\x01 \x02(\t'
)




_MESSAGE_DETECTION = _descriptor.Descriptor(
  name='message_detection',
  full_name='message_detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='message_detection.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['message_detection'] = _MESSAGE_DETECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

message_detection = _reflection.GeneratedProtocolMessageType('message_detection', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_DETECTION,
  '__module__' : 'message_detection_pb2'
  # @@protoc_insertion_point(class_scope:message_detection)
  })
_sym_db.RegisterMessage(message_detection)


# @@protoc_insertion_point(module_scope)
