# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_image.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x13message_image.proto\"B\n\rmessage_image\x12\r\n\x05width\x18\x01 \x02(\r\x12\x0e\n\x06height\x18\x02 \x02(\r\x12\x12\n\nimage_data\x18\x03 \x02(\x0c'
)




_MESSAGE_IMAGE = _descriptor.Descriptor(
  name='message_image',
  full_name='message_image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='message_image.width', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='message_image.height', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='message_image.image_data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['message_image'] = _MESSAGE_IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

message_image = _reflection.GeneratedProtocolMessageType('message_image', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_IMAGE,
  '__module__' : 'message_image_pb2'
  # @@protoc_insertion_point(class_scope:message_image)
  })
_sym_db.RegisterMessage(message_image)


# @@protoc_insertion_point(module_scope)
