# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_ROI.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_ROI.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x11message_ROI.proto\"&\n\x05point\x12\r\n\x05width\x18\x01 \x02(\r\x12\x0e\n\x06height\x18\x02 \x02(\r\")\n\x0bmessage_ROI\x12\x1a\n\nROI_points\x18\x01 \x03(\x0b\x32\x06.point'
)




_POINT = _descriptor.Descriptor(
  name='point',
  full_name='point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='point.width', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='point.height', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=59,
)


_MESSAGE_ROI = _descriptor.Descriptor(
  name='message_ROI',
  full_name='message_ROI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ROI_points', full_name='message_ROI.ROI_points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=102,
)

_MESSAGE_ROI.fields_by_name['ROI_points'].message_type = _POINT
DESCRIPTOR.message_types_by_name['point'] = _POINT
DESCRIPTOR.message_types_by_name['message_ROI'] = _MESSAGE_ROI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

point = _reflection.GeneratedProtocolMessageType('point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'message_ROI_pb2'
  # @@protoc_insertion_point(class_scope:point)
  })
_sym_db.RegisterMessage(point)

message_ROI = _reflection.GeneratedProtocolMessageType('message_ROI', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_ROI,
  '__module__' : 'message_ROI_pb2'
  # @@protoc_insertion_point(class_scope:message_ROI)
  })
_sym_db.RegisterMessage(message_ROI)


# @@protoc_insertion_point(module_scope)
